### PR TITLE
Use asynchronous version of hipMemset

### PR DESCRIPTION
**Pull request by cloudhan**
make kernel launch impl follow the stream config from caller

### CODE REVIEW

**Comment by carlushuang** [comment]
LGTM

**Comment by carlushuang** [comment]
@cloudhan have you tested the speed, do you see this method will increase the overall performance, or decrease the performance

**Comment by cloudhan** [comment]
No strict test for ck itself. The problem is that I observed slightly sparsed kernel launch in onnxruntime inference profiling trace. This improve it. Note that in ck's `launch_and_time_kernel`, it does not include these type of buffer initialialization in its timing, so the result won't change in ckProfiler.

**Comment by cloudhan** [comment]
OK. This also accidentally fixed a bug. Without it, the hipMemset will not correctly initialize the buffer in multistream scenario, caused my whisper model to produce garbage with splitk integrated. With this, the issue is now fixed.

**Comment by cloudhan** [comment]
@carlushuang FYI, https://github.com/ROCmSoftwarePlatform/composable_kernel/blob/d4c84256f790d210ea5c952cb18ad13542f6c698/include/ck/tensor_operation/gpu/device/impl/device_batchnorm_forward_impl.hpp#L396 is not corrected in this PR. It requires some level of API change.

**Review by zjing14 — APPROVED** [review]

**Pull request merged**
