### PR TITLE
Disable XDL kernels on unsupported HW Add ck::is_xdl_supported

### PR DESCRIPTION
**Pull request by bartekxk**

### CODE REVIEW

**Comment by bwroblew** [comment]
Please, do not merge this PR without an approval from @zjing14

**Review by asroy — DISMISSED** [review]

**Comment by asroy** [comment]
@bartekxk Please resolve merge conflict and we can merge this PR

**Comment by bwroblew** [comment]
@asroy we rebased the change, could you merge that, please?

**Comment by bwroblew** [comment]
Rebased it again, since there was another conflict

**Comment by illsilin** [comment]
Oh, I just noticed this PR is from a personal repo, so it didn't trigger the CI.
Can you move it into a branch in the rocm repo so that it gets tested?
Or would you like me to do it?

**Comment by bwroblew** [comment]
> Oh, I just noticed this PR is from a personal repo, so it didn't trigger the CI. Can you move it into a branch in the rocm repo so that it gets tested? Or would you like me to do it?

Hey @illsilin, this PR is not from a personal repo, see that it's from the `bwroblew/xdl_support` branch in the CK repo (not the forked one). It has been first created from my personal fork and has been already merged to that branch (https://github.com/ROCmSoftwarePlatform/composable_kernel/pull/765) in CK.
I guess there was some delay with triggering CI but it is running now.

**Comment by illsilin** [comment]
Yep, looks like CI ran successfully.
We should merge this. It's been sitting waiting too long!

**Review by illsilin — APPROVED** [review]

**Pull request merged**
