### PR TITLE
Fix cmake warnings

### PR DESCRIPTION
**Pull request by bartekxk**
#1330

### CODE REVIEW

**Review by aosewski — DISMISSED** [review]

**Comment by yxsamliu** [comment]
I saw another warning caused error when I try to verify this PR using clang trunk:

In file included from /home/yaxunl/git/composable_kernel/library/src/tensor_operation_instance/gpu/image_to_column/device_image_to_column_gnwc_1d_instance.cpp:4:
In file included from /home/yaxunl/git/composable_kernel/library/include/ck/library/tensor_operation_instance/gpu/conv_tensor_rearrange/device_image_to_column_instance.hpp:6:
In file included from /home/yaxunl/git/composable_kernel/include/ck/tensor_operation/gpu/device/impl/device_image_to_column_impl.hpp:9:
In file included from /home/yaxunl/git/composable_kernel/include/ck/tensor_operation/gpu/grid/gridwise_tensor_rearrange.hpp:12:
/home/yaxunl/git/composable_kernel/include/ck/tensor_operation/gpu/block/blockwise_gemm_xdlops.hpp:343:42: error: a template argument list is expected after a name prefixed by the template keyword [-Wmissing-template-arg-list-after-template-kw]
  343 |                     xdlops_gemm.template Run(
      |                                          ^
/home/yaxunl/git/composable_kernel/include/ck/tensor_operation/gpu/block/blockwise_gemm_xdlops.hpp:533:46: error: a template argument list is expected after a name prefixed by the template keyword [-Wmissing-template-arg-list-after-template-kw]
  533 |                         xdlops_gemm.template Run(
      |                                              ^
/home/yaxunl/git/composable_kernel/include/ck/tensor_operation/gpu/block/blockwise_gemm_xdlops.hpp:966:42: error: a template argument list is expected after a name prefixed by the template keyword [-Wmissing-template-arg-list-after-template-kw]
  966 |                     xdlops_gemm.template Run(
      |                                          ^

**Comment by yxsamliu** [comment]
LGTM. You may consider adding `-Wno-missing-template-arg-list-after-template-kw` in a separate PR.

**Comment by yxsamliu** [comment]
verified with llvm trunk. build successful.

**Comment by bartekxk** [comment]
> verified with llvm trunk. build successful.

Thanks!

**Review by aosewski — APPROVED** [review]

**Pull request merged**
