### PR TITLE
[Navi3x] Add int8 gemm_bilinear instances

### PR DESCRIPTION
**Pull request by aska-0096**
### Add instance & examples:
1. Add example
2. Add instances for NN, TN, TT, TN layout

### Hacky
Bilinear element-wise op use float type as struct member variable which not compatible with int8 type, all alpha/beta would be 1 in int8 gemm bilinear kernel

###  Need help
1. Build profiler need have a flag to determine which architecture would profiler would be used on.
2. Should isolate the CMake target to ensure it only works on GFX110X GPUs
https://github.com/ROCmSoftwarePlatform/composable_kernel/blob/1c97db8abed923e12159c46cd9552c54bf49b5fc/library/src/tensor_operation_instance/gpu/gemm_bilinear/CMakeLists.txt#L6-L9

cc. @zjing14

### CODE REVIEW

**Comment by zjing14** [comment]
~~Hold this PR until int8 compilation issue fix~~

**Comment by zjing14** [comment]
@aska-0096 Please resolve the conflict.

**Comment by aska-0096** [comment]
> @aska-0096 Please resolve the conflict.

Solved.

**Comment by zjing14** [comment]
@aska-0096 This is no change with develop. Does this PR is covered by another PR already?

**Comment by aska-0096** [comment]
> @aska-0096 This is no change with develop. Does this PR is covered by another PR already?

You are right, it seems like this PR covered by PR#746.
We can close this PR.

**Pull request closed without merging**
