### PR TITLE
Add SplitK support into BMM V3

### PR DESCRIPTION
**Pull request by zjing14**

### CODE REVIEW

**Review by bartekxk — COMMENTED** [review]
LGTM I will create second branch to run CI

**Comment by bartekxk** [comment]
Ran CI under #1729

**Comment by bartekxk** [comment]
Hi @zjing14 , CI failed during example/24_batched_gemm/batched_gemm_xdl_fp32.cpp: compilation.

**Comment by zjing14** [comment]
@bartekxk Fixed. Please try CI again.

**Comment by bartekxk** [comment]
Hi, now `profile_gemm_universal_batched.cpp:88:11: error: unused type alias 'F8' ` is failing

**Comment by zjing14** [comment]
@bartekxk Pushed a fix, please give a try, thanks.

**Comment by bartekxk** [comment]
Merged under #1729 , thank you!

**Pull request closed without merging**
