### PR TITLE
Fix instances dtype check

### PR DESCRIPTION
**Pull request by bartekxk**
This PR:

- Fix examples and tests cmake to remove sources with multiple dtypes in file name when at least one of them is not supported.
- Fixed grouped_conv3d_bwd_weight CMakeLists.txt

### CODE REVIEW

**Comment by zjing14** [comment]
@bartekxk could you check if this PR https://github.com/ROCmSoftwarePlatform/composable_kernel/pull/974 can resolve your problem.

**Comment by bartekxk** [comment]
> @bartekxk could you check if this PR #974 can resolve your problem.

@zjing14 Looks like it cover some part of my fixes. I will wait after merge Your PR and then I will sync with this.

**Comment by zjing14** [comment]
@bartekxk Could you take a look if my PR #974 resolves your issues.

**Comment by bartekxk** [comment]
> @bartekxk Could you take a look if my PR #974 resolves your issues.

I synchronized this PR with Your change. It solved some of the problems. I updated PR comment.

**Review by illsilin — APPROVED** [review]
Looks good!

**Pull request merged**
