### PR TITLE
Check compiler flags before using

### PR DESCRIPTION
**Pull request by trixirt**
The user's compiler may not support these flags, so check. Resolves failures on Fedora.

### CODE REVIEW

**Comment by illsilin** [comment]
Unfortunately, this PR breaks 2 tests in our CI:

[2024-07-25T21:33:39.047Z] The following tests FAILED:
[2024-07-25T21:33:39.047Z] 	251 - test_gemm_universal (Failed)
[2024-07-25T21:33:39.047Z] 	268 - test_grouped_convnd_fwd (Failed)

Please make sure all tests are passing, then re-submit.

**Comment by trixirt** [comment]
I can not see the details on the failures, on a working build with a compiler that supported these options this should have been a noop. is a non working compiler being used and the warnings of unsupported cmd line options being ignored later?

**Comment by illsilin** [comment]
The tests failed with the default ROCm6.1 compiler.

**Comment by illsilin** [comment]
Let's see how this is going to work with rocm6.2 compiler.

**Comment by illsilin** [comment]
Looks like the cause of the failures was the comma in the original commit:

check_cxx_compiler_flag("-mllvm -enable-post-misched=0", HAS_ENABLE_POST_MISCHED)

**Review by illsilin — APPROVED** [review]

**Pull request merged**
