### PR TITLE
add vector_type support into thread_copy_v3r1

### PR DESCRIPTION
**Pull request by zjing14**

### CODE REVIEW

**Review by carlushuang — DISMISSED** [review]
LGTM

**Review by geyyer — DISMISSED** [review]
LGTM! Noob question: what is the benefit of the vector_type support if we loop over vector elements anyways and apply element-wise op one at a time?

**Review by carlushuang — DISMISSED** [review]
LGTM

**Review by geyyer — APPROVED** [review]
LGTM!

**Pull request merged**
