### PR TITLE
[GEMM] Set enable-post-misched=0 as default compile option

### PR DESCRIPTION
**Pull request by aska-0096**
This PR set "-mllvm -enable-post-misched=0" as default compile option of CK.
This option will improve gemm_universal performance and ensure the correctness.

### CODE REVIEW

**Comment by aska-0096** [comment]
It seems that option doesn't compatible to **clang++** in CI codegen test.
Hi @illsilin, may I ask the reason behind CI codegen use **clang++** compiler?
Hi @zjing14 , are our users and customers all use hipcc as compiler?

**Comment by aska-0096** [comment]
<Convert to draft>
The new compile flag not support in rocm6.0 clang++( latest release), but it should be. Compiler team is checking the issue.

cc @zjing14

**Comment by illsilin** [comment]
Most of the customers build CK with clang directly and dislike hipcc because it is not transparent about what it does behind the scenes. It is AMD policy to get all rocm components to abandon hipcc and move to clang by 6.2 release. We have started using clang as the default compiler for our builds since November 2023.

**Comment by aska-0096** [comment]
> Most of the customers build CK with clang directly and dislike hipcc because it is not transparent about what it does behind the scenes. It is AMD policy to get all rocm components to abandon hipcc and move to clang by 6.2 release. We have started using clang as the default compiler for our builds since November 2023.

Thanks for explaining.
I tested this branch on ROCm 6.1 and found no problems. It seems that our compiler solved the problem on this version.
Is it possible to update the CI docker to ROCm 6.1 which was released today?

**Comment by illsilin** [comment]
We can definitely upgrade our default docker and compiler to rocm6.1, however, it's likely that some customers will continue to use older compiler versions for some time. So I would be a little worried to use compiler flags that will cause build failures with older rocm versions. Perhaps, we can implement these flags as an option in our CI and set the default to ON, instead of hardcoding them in the cmake file?

**Comment by illsilin** [comment]
The 2fix had been merged in PR #1250, so this one is no longer required.

**Pull request closed without merging**
