### PR TITLE
Fix gemm splik 

### PR DESCRIPTION
**Pull request by PeixuanZuo**

### CODE REVIEW

**Comment by PeixuanZuo** [comment]
@illsilin Could you please review this pr? Thanks.

**Comment by zjing14** [comment]
@PeixuanZuo Could you create the branch in the CK repo instead of forked repo? Otherwise, the PR won't run on our CI.

**Comment by illsilin** [comment]
Why do you think that it's a bug?

**Comment by PeixuanZuo** [comment]
> Why do you think that it's a bug?

If we want to use both fp8 and fp16 data types, we need to make sure they are both enabled. Please correct me if I've misunderstood the logic.

**Comment by illsilin** [comment]
Well, almost 99% of the kernels are only dealing with one datatype. We have only added a handful of kernels that will use different datatypes as inputs. 
The purpose of the DTYPES filters is primarily to reduce the build time for the entire CK library, especially when building for multiple targets. So we don't necessarily want to rip out every mention of a data type in case we are not planning to use it, we just don't want to build any instances, test, or examples that are using that data type EXCLUSIVELY.
However, if an instance is using more than one data type, and one of those types is selected for the build, we have decided that we will build all the instances that use that data type, even if the other type was not selected. Hence the "or" condition in the code.

**Comment by PeixuanZuo** [comment]
Thanks for your details explanation. This fix is to solve a build error. I will open a new issue for the problem I encountered. Thank you.

**Comment by PeixuanZuo** [comment]
I found an existing issue(https://github.com/ROCmSoftwarePlatform/composable_kernel/issues/928), which is the issue I encountered.

**Pull request closed without merging**
