### PR TITLE
get rid of gfx900/906, set rocm5.7 as default

### PR DESCRIPTION
**Pull request by illsilin**
This change will remove the gfx900 and gfx906 targets by default if the GPU_TARGETS macro is not set.
Also, will use rocm5.7 by default when building the dockerfile.
Also fixed a syntax issue introduced by previous commit.

### CODE REVIEW

**Review by zjing14 — APPROVED** [review]

**Comment by sjnewbury** [comment]
Why remove gfx900?  I have a patch to fix gfx900 support and was going to create a PR, but if it is being stripped out that is problematic!

Please don't remove code for "unsupported" GPUs.

**Comment by junliume** [comment]
> Why remove gfx900? I have a patch to fix gfx900 support and was going to create a PR, but if it is being stripped out that is problematic!
> 
> Please don't remove code for "unsupported" GPUs.

Primarily due to the kernel cache binary size has exceeded some limits on some platforms. We can still use `-GPU_TARGETS=""` to set the target specifically. @illsilin we should update documentation.

**Comment by sjnewbury** [comment]
> > Why remove gfx900? I have a patch to fix gfx900 support and was going to create a PR, but if it is being stripped out that is problematic!
> > Please don't remove code for "unsupported" GPUs.
> 
> Primarily due to the kernel cache binary size has exceeded some limits on some platforms. We can still use `-GPU_TARGETS=""` to set the target specifically. @illsilin we should update documentation.

Actually, the -DGPU_TARGETS="" gets filtered by the GPU list.  I noticed because of build failure where I'm building for just GFX900.  Another commit has also removed GFX900 conditions throughout the project.  I do have it building with GFX900 support, if I might a PR restoring the functionality, presumably my chances of getting it committed would be higher if I sort out the issue of GPU_TARGETS getting filtered when set explicitly?

**Comment by illsilin** [comment]
@sjnewbury you can still build CK without any problems for gfx900 by setting -DGPU_TARGETS="gfx900" on the cmake command line. 
All we did was remove the gfx900 and gfx906 from the list of DEFAULT targets which is used when no target is specified explicitly for cmake. This in no way affects CK functionality on gfx900/gfx906.

**Comment by sjnewbury** [comment]
@illsilin Have you tried gfx900 build?  There's are build failures due to gfx900 not being included in various "#if defined' blocks (which is failing due to blocks not being enabled, which maybe it shouldn't be for gfx900, I'm not sure?), along with the lack of a fallback implementation (which I've written) for the asm (due to gfx900 lacking the instructions) in `include/ck/utility/amd_inline_asm.hpp`.

In the CMakeLists.txt file, the comment says : "used in case GPU_TARGETS is not set on command line", but instead unconditionally uses `set(GPU_TARGETS "${DEFAULT_GPU_TARGETS}" CACHE STRING " " FORCE)` and `set(AMDGPU_TARGETS "${DEFAULT_GPU_TARGETS}" CACHE STRING " " FORCE)`.  See below:

```
message("checking which targets are supported")
#This is the list of targets to be used in case GPU_TARGETS is not set on command line
#These targets will be filtered and only supported ones will be used
#Setting GPU_TARGETS on command line will override this list
if(NOT PROFILER_ONLY)
    rocm_check_target_ids(DEFAULT_GPU_TARGETS
        TARGETS "gfx908;gfx90a;gfx940;gfx941;gfx942;gfx1030;gfx1100;gfx1101;gfx1102")
else()
    add_definitions(-DPROFILER_ONLY)
    set(GPU_TARGETS "" CACHE STRING "" FORCE)
    if(GPU_TARGETS)
        message(FATAL_ERROR "For PROFILE_ONLY build, please do not set GPU_TARGETS, use GPU_ARCH = gfx90, gfx94, gfx10, or gfx11")
    endif()
    if(GPU_ARCH MATCHES "gfx90")
        rocm_check_target_ids(DEFAULT_GPU_TARGETS TARGETS "gfx908;gfx90a")
    elseif(GPU_ARCH MATCHES "gfx94")
        rocm_check_target_ids(DEFAULT_GPU_TARGETS TARGETS "gfx940;gfx941;gfx942")
    elseif(GPU_ARCH MATCHES "gfx10")
        rocm_check_target_ids(DEFAULT_GPU_TARGETS TARGETS "gfx1030")
    elseif(GPU_ARCH MATCHES "gfx11")
        rocm_check_target_ids(DEFAULT_GPU_TARGETS TARGETS "gfx1100;gfx1101;gfx1102")
    else()
        message(FATAL_ERROR "For PROFILE_ONLY build, please specify GPU_ARCH as gfx90, gfx94, gfx10, or gfx11")
    endif()
    set(GPU_TARGETS "${DEFAULT_GPU_TARGETS}" CACHE STRING " " FORCE)
endif()

message("Supported GPU_TARGETS= ${DEFAULT_GPU_TARGETS}")

set(AMDGPU_TARGETS "${DEFAULT_GPU_TARGETS}" CACHE STRING " " FORCE)
```

**Pull request merged**
