### PR TITLE
fix build issues on gfx1100 alone

### PR DESCRIPTION
**Pull request by junliume**
#1357

### CODE REVIEW

**Comment by illsilin** [comment]
The changes are made to 2 files with xdl instances. Those files should never get built for gfx11 targets at all.

**Comment by junliume** [comment]
> The changes are made to 2 files with xdl instances. Those files should never get built for gfx11 targets at all.

with `-DGPU_TARGETS="gfx1100" -DINSTANCES_ONLY=ON` I think the second option overrides the former :(

**Comment by illsilin** [comment]
I see. Yes, setting GPU_TARGETS and INSTANCES_ONLY flags would break the cmake logic.
If you need to build CK just for gfx1100, I recommend just removing the INSTANCES_ONLY.
I may need to eventually come up with another build flag, so we should be able to build just instances for a select target and introduce some new flag to build the libraries for all supported targets.

**Comment by junliume** [comment]
@illsilin  this problem also manifests when we set 
> CXX=/opt/rocm/bin/amdclang++ cmake -DCMAKE_PREFIX_PATH=/opt/rocm -DCMAKE_BUILD_TYPE=Release -DGPU_TARGETS="gfx1100;gfx90a;gfx942" ..

Hence `GPU_TARGETS="gfx1100;gfx90a;gfx942"`

**Comment by junliume** [comment]
replaced by #1372

**Pull request closed without merging**
