### PR TITLE
update layernorm

### PR DESCRIPTION
**Pull request by ltqin**

### CODE REVIEW

**Review by aska-0096 — DISMISSED** [review]
LGTM

**Review by carlushuang — CHANGES_REQUESTED** [review]
1. API naming issue, we can't have `layernorm2d_fwd_fp16`, `layernorm2d_fwd_fp16`. Need have a single API `layernorm2d_fwd` which is originally rocking version
2. need use `trait` to dispatch API. This PR completely remove this
3. `p_mean`, `p_invStd` removed??
-> this PR need more change to merge to public

**Review by spolifroni-amd — DISMISSED** [review]
Nothing to do on docs side.

**Review by carlushuang — DISMISSED** [review]
LGTM

**Review by carlushuang — DISMISSED** [review]
LGTM

**Review by carlushuang — APPROVED** [review]
LGTM

**Pull request merged**
