### PR TITLE
[GEMM] gemm_universal related optimization

### PR DESCRIPTION
**Pull request by aska-0096**
1. add a flag expect better register allocation
2. include global atomic bf16 mentioned in #1427 
3. Add 256x256x128 tile for fp8 gemm
4. optimize OOB check strategy, reduce conditional mask usage and instance number of gemm_multiply_multiply.

### CODE REVIEW

**Comment by aska-0096** [comment]
cc @zjing14 @illsilin

**Comment by junliume** [comment]
@aska-0096 there are some CI issues. BTW~ are these changes required for `ROCm 6.2.1`?
```
/home/jenkins/workspace/mposable_kernel_gemm_opt_rocm6.2/library/src/tensor_operation_instance/gpu/grouped_conv3d_bwd_weight_scale/xdl/device_grouped_conv3d_bwd_weight_xdl_scale_ndhwgc_gkzyxc_ndhwgk_f16_comp_bf8_fp8_instance.cpp:25:69: error: use of undeclared identifier 'BF8'

[2024-08-09T03:26:54.573Z]    25 |                                                                     BF8,

[2024-08-09T03:26:54.573Z]       |                                                                     ^

[2024-08-09T03:26:54.573Z] 1 error generated when compiling for gfx1100.
```

**Comment by aska-0096** [comment]
> @aska-0096 there are some CI issues. BTW~ are these changes required for `ROCm 6.2.1`?
> 
> ```
> /home/jenkins/workspace/mposable_kernel_gemm_opt_rocm6.2/library/src/tensor_operation_instance/gpu/grouped_conv3d_bwd_weight_scale/xdl/device_grouped_conv3d_bwd_weight_xdl_scale_ndhwgc_gkzyxc_ndhwgk_f16_comp_bf8_fp8_instance.cpp:25:69: error: use of undeclared identifier 'BF8'
> 
> [2024-08-09T03:26:54.573Z]    25 |                                                                     BF8,
> 
> [2024-08-09T03:26:54.573Z]       |                                                                     ^
> 
> [2024-08-09T03:26:54.573Z] 1 error generated when compiling for gfx1100.
> ```

Hi Jun, I'm working on that, basically I want to turn off CK_ENABLE_FP8 and CK_ENABLE_BF8 Flag on non-gfx94 device.

Not specific to ROCm version, maybe I can change the PR name.

**Comment by aska-0096** [comment]
Need some extra work to limit the compiler flag "-greedy-reverse-local-assignment" scope

**Comment by aska-0096** [comment]
> Need some extra work to limit the compiler flag "-greedy-reverse-local-assignment" scope

Done, we can merge this PR if everything looks good.
I add the flag `-mllvm -greedy-reverse-local-assignment=1 ` only to gemm_universal related operators in ckProfiler so that it will not affect other operators.
cc. @illsilin

**Review by carlushuang — APPROVED** [review]
LGTM

**Pull request merged**
