### PR TITLE
Disable Werror to ignore xnack+ warnings

### PR DESCRIPTION
**Pull request by arvindcheru**
Changes Proposed:
- When ASAN features are enabled, this change helps to ignore the xnack+ warning to consider as errors

### CODE REVIEW

**Comment by illsilin** [comment]
I think instead of removing -Werror, we should add the -Wno-option-ignored flag. Wasn't that the plan?

**Comment by arvindcheru** [comment]
> I think instead of removing -Werror, we should add the -Wno-option-ignored flag. Wasn't that the plan?

Thanks for the comments, Will check this and get back

**Comment by arvindcheru** [comment]
> > I think instead of removing -Werror, we should add the -Wno-option-ignored flag. Wasn't that the plan?
> 
> Thanks for the comments, Will check this and get back

Kindly review the latest patch this includes comments mentioned, Please approve/merge to proceed on this change. Thanks

**Review by illsilin — APPROVED** [review]
I think this is safe to merge.

**Pull request merged**
