### PR TITLE
disabling some fp8 gemm instances to reduce build time

### PR DESCRIPTION
**Pull request by illsilin**
Removed the default gemm instances and disabled the experimental v2 pipeline for fp8 gemms.
This should bring the build times back to ~15 minutes per target.

### CODE REVIEW

**Comment by junliume** [comment]
> Removed the default gemm instances and disabled the experimental v2 pipeline for fp8 gemms. This should bring the build times back to ~15 minutes per target.

@illsilin @zjing14 I'd hope that we can fix the issue than to disable some functionalities. At least the workaround should have a very clear lifecycle on Day 0.

**Comment by illsilin** [comment]
@junliume I don't think that's the issue. Someone was experimenting with different algorithms for fp8 gemms and forgot how adding more instances may affect the build times. So we're just cleaning up the less efficient instances here.

**Comment by illsilin** [comment]
Hey guys, the tests have all passed and the build time is greatly reduced:
http://micimaster.amd.com/blue/organizations/jenkins/MLLibs%2Fcomposable_kernel/detail/lwpck-1097/3/pipeline/104

**Review by junliume — DISMISSED** [review]
@illsilin  do we plan to add those instances back? But now with more and smaller files so that the impact on build time should be less?

**Review by zjing14 — APPROVED** [review]

**Pull request merged**
