### PR TITLE
[CK TILE] Add gemm compute pipeline v3

### PR DESCRIPTION
**Pull request by bartekxk**

### CODE REVIEW

**Comment by aosewski** [comment]
Will add this pipeline to unit-test in next PR after #1647 would have been merged as it updates unit-tests structure.

**Review by bartekxk — COMMENTED** [review]
lgtm

**Review by aosewski — APPROVED** [review]

**Comment by aosewski** [comment]
Let's wait for CI to pass.

**Review by jakpiase — APPROVED** [review]
LGTM

**Pull request merged**
