### PR TITLE
Batched GEMM Multiple D based on Universal GEMM

### PR DESCRIPTION
**Pull request by bartekxk**

### CODE REVIEW

**Comment by bartekxk** [comment]
Hi @zjing14 , I squashed commits and ran clang-format in this PR based on changes from #1614

**Comment by bartekxk** [comment]
Hi @zjing14 , build of profile_gemm_universal_batched failed. Could you fix that?

**Comment by zjing14** [comment]
@bartekxk Could you share what is the failure? I cannot access the CI log

**Comment by bartekxk** [comment]
> @bartekxk Could you share what is the failure? I cannot access the CI log

`ld.lld: error: undefined symbol: _ZN2ck16tensor_operation6device8instance82add_device_batched_gemm_xdl_universal_f8_f8_bf16_mk_nk_mn_mem_v1_default_instancesERSt6vectorISt10unique_ptrINS1_25DeviceBatchedGemmV2MultiDINS_13tensor_layout4gemm8RowMajorENS7_11ColumnMajorENS_5TupleIJEEES8_DB8_SC_SB_tNS0_12element_wise11PassThroughESE_SE_EESt14default_deleteISF_EESaISI_EE
 referenced by profile_gemm_universal_batched.cpp`

**Review by aosewski — APPROVED** [review]

**Pull request merged**
